### ISSUE TITLE
RFE: improved search for figures

### ISSUE THREAD

**Issue by carandraug** [ome/figure#146]
Our users are starting to use figure a lot. With an increased in the number of figures, comes an organization issue because it's hard to find the figure they want. Example, consider the following 5 figure names:

* sggmRNA_sgg_NMJ_Nerve_single plane
* sggmRNA_sgg_s5_NMJ_single planes
* sgg_sggprobes_NMJ_zoom
* sgg_sggprobes_NMJ_zoom
* sgg_Rab11_Venus_NMJ_zoom

None of them will be listed by searching for "sgg NMJ".  Only one will using "sgg_NMJ".  Again, none will show up with "NMJ_sgg".

I understand that the search is done in the name, I'm just arguing that a name is not enough.  This becomes worse when all the figures are at the same level, there's no filesystem-like hierarchy (but I would prefer a tag system to a hierarchic organization).

In OMERO it's possible to tag images and datasets. Something like that would be pretty sweet.

**Comment by will-moore** [comment]
The simplest fix for the scenario above is that filtering figures with "sgg NMJ" will find all the ones that contain "sgg" AND "NMJ" (splitting the search text on whitespace).
That wouldn't change the results for "sgg_NMJ" or "NMJ_sgg" but hopefully that's OK?

A full tagging workflow is possible but would be quite a bit more work. And it would add more steps to the user's workflow.
I'll improve the searching as suggested above and see how far that gets us.

**Comment by will-moore** [comment]
I opened a PR with the filtering improvement at https://github.com/ome/figure/pull/147

**Comment by will-moore** [comment]
I'm going to assume that this issue is basically fixed with #147. If you still feel that we need a full tagging support then please go ahead and open another issue. Thanks.
